config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :dishes
  resources :users
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  root  'sessions#new'

  scope module: :api, path: 'api' do
    resources :clients
    resources :dishes
    resources :order_details
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :password, presence: true
  validates :mail, presence: true, email: true, uniqueness: true

  def image_url
    @password1 = false
  end

  enum role: { administrator: 0, chef: 1 }
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_user, only: %i[show edit update destroy]

    def index
      @users = User.all
    end

    def show; end

    def new
      @user = User.new
    end

    def edit; end

    def create
      @user = User.find_by(name: params[:name])

      if @user.nil? == false
        if @user.password == params[:password] && @user != :undefined
          @isValidate = true
          render 'api/users/showValidates', status: :created
        else
          @isValidate = false
          render 'api/users/showValidates', status: :created
        end
      else
        @isValidate = false
        render 'api/users/showValidates', status: :created
      end
    end

    def update
      if @user.update(user_params)
        render 'api/users/show', status: :ok
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @user.destroy

      render 'api/users/show', status: :ok
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'User was successfully created.'

      redirect_to user_url(@user)
    else
      flash[:danger] = 'Check the information'
      redirect_to new_user_path
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'User was successfully updated.'
      redirect_to user_url(@user)
    else
      flash[:danger] = 'Check the information'
      redirect_to new_user_path
    end
  end

  def destroy
    @user.destroy
    flash[:success] = 'User was successfully destroyed.'
    redirect_to users_url
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password, :mail, :address, :role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def roles
    User.roles.keys.map do |role|
      [t("activerecord.attributes.user.roles.#{role}"), role]
    end
  end
end

app/views/users/_form.html.haml
= render "layouts/flash"
.div.m-4
  .page.header_new
    = form_for @user, validate: true do |f|
      .form-group.ml-4.mr-4
        = f.label t('activerecord.attributes.user.name'), class: "form-label required"
        = f.text_field :name, autofocus: true, class: "form-control"
      .form-group.ml-4.mr-4
        = f.label t('activerecord.attributes.user.password'), class: "form-label required"
        = f.password_field :password, autofocus: true, class: "form-control"
      .form-group.ml-4.mr-4
        = f.label  t('activerecord.attributes.user.mail'), class: "form-label required"
        = f.text_field :mail, autofocus: true, class: "form-control"
      .form-group.ml-4.mr-4
        = f.label t('activerecord.attributes.user.address'), class: "form-label required"
        = f.text_field :address, autofocus: true, class: "form-control"
      .form-group.ml-4.mr-4 
        = f.label t('activerecord.attributes.user.role'), class: "form-label required"
        = f.select(:role, options_for_select(roles, @user.role),
                            {prompt: t('application.select')}, class: 'form-control')
        
      .row
        .offset-3.col-3
          = link_to t('application.back'), users_path, class: "button_Back button_Back"
        .col-3
          = button_tag t('application.save'), class: "button_saving button_Back", 'data-disable-with': t('application.saving')

app/views/users/edit.html.haml
.page_header
  %h1.mb-4
    = "Editar Usuario"
= render "form"

app/views/users/index.html.haml
= render "layouts/flash"
.div.m-4
  .page.header
    %p{:style => "color: green"}= notice
    %h1.mb-4
      = t('application.list_of', model: t('activerecord.modules.user.other'))
  %div
    = search_form_for @q do |f|
    
      \#{f.search_field :name_cont, :type => "text2"}
      = button_tag( :class => "button button2") do
        Buscar
        %i.fa-solid.fa-magnifying-glass

      .float-right
        = link_to t('application.new', model: t('activerecord.modules.user.one')), new_user_path, class: "button1 button2"
  %div
    %table.table.table-striped
      %thread
        %tr
          %th= t('activerecord.attributes.user.name')
          %th= t('activerecord.attributes.user.mail')
          %th= t('activerecord.attributes.user.address')
          %th= t('activerecord.attributes.user.role')
          %th
          %th
          %th
      %tbody
        - @users.each do |user|
          %tr
            %td= user.name
            %td= user.mail
            %td= user.address
            %td= t("activerecord.attributes.user.roles.#{user.role}")
            %td
              = link_to  user_path(user) do
                %span{:title => t('application.show')}
                  %i.fa-black.fa-regular.fa-eye.fa-1.5x
                  
            %td
              = link_to edit_user_path(user) do
                %span{:title => t('application.edit')}
                  %i.fa-green.fa-regular.fa-pen-to-square        

            %td 
              = link_to user, method: :delete do
                %span{:title => t('application.delete')}
                  %i.fa-red.fa-solid.fa-trash                                  

app/views/users/new.html.haml
.page_header
  %h1.mb-4
    = t('application.new', model: t('activerecord.modules.user.one'))
= render "form"

app/views/users/show.html.haml
= render "layouts/flash"
.div.m-4
  .page.header_new
    %h2 
      =t('activerecord.modules.user.one')
    .card
      %img{:height => "250", :src => "https://img.icons8.com/windows/512/contacts.png", :width => "250"}/   
      .container
        %h5
          =t('activerecord.attributes.user.name')
          %p 
            = @user.name
        %h5 
          =t('activerecord.attributes.user.mail')
        %h5 
          %p 
            = @user.mail
        %h5
          =t('activerecord.attributes.user.address')
        %h5 
          %p 
            =  @user.address
        %h5
          =t('activerecord.attributes.user.role')
        %h5 
          %p 
            =  @user.role
    .row.mt-3
      .offset-3.col-3
        = link_to t('application.back'), users_path, class: "button_Back button_Back"