config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :dishes
  resources :users
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  root  'sessions#new'

  scope module: :api, path: 'api' do
    resources :clients
    resources :dishes
    resources :order_details
    resources :users
  end
end

app/models/client.rb
class Client < ApplicationRecord
  validates :email, presence: true, email: true
  validates :name, length: { maximum: 10 }, presence: true
  validates :last_name, length: { maximum: 15 }, presence: true
  enum block: { disabled: 0, enable: 1}
end

app/controllers/api/clients_controller.rb
module Api
  class ClientsController < ApplicationController

    skip_before_action :verify_authenticity_token
    before_action :set_client, only: %i[show edit update]
    

    def show; end

    def new
      @client = Client.new
    end

    def edit; end

    def create
      @client = Client.new(client_params)

      if @client.save
        render 'api/clients/index', status: :created
      else
        render json: @client.errors, status: :unprocessable_entity
      end
    end

    def update
      if @client.update(client_params)
        render 'api/clients/show', status: :created
      else
        render json: @clients.errors, status: :unprocessable_entity
      end
    end

    def destroy
      @client.destroy

      render 'api/clients/show', status: :ok
    end

    private

    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name, :last_name, :adress, :email, :password)
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[show edit update destroy]

  def index
    @q = Client.ransack(params[:q])
    @clients = @q.result
  end

  def show; end

  def new
    @client = Client.new
  end

  def edit; end

  def create
    @client = Client.new(client_params)

    if @client.save
      flash[:success] = 'Client was successfully created.'
      redirect_to client_url(@client)

    else
      flash[:danger] = 'Ha ocurrido un problema, intente nuevamente'
      redirect_to new_client_path

    end
  end

  def update
    if @client.update(client_params)
      flash[:success] = 'Client was successfully updated.'
      redirect_to client_url(@client)

    else
      flash[:danger] = 'Ha ocurrido un problema, intente nuevamente'
      redirect_to new_client_path

    end
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:block, :name, :last_name, :pasword, :email, :adress)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
  def method_Block
    Client.blocks.keys.map do |block|
      [t("activerecord.attributes.dish.isEnable.#{block}"), block]
    end
  end
end

app/views/clients/_form.html.haml
.div.m-4
  .page.header_new
    = form_for @client, validate: true do |f|
      .form-group.ml-4.mr-4
        = f.label t('activerecord.attributes.user.name'), class: "form-label required" 
        %div
          = f.label @client.name, class: "form-control"
      .form-group.ml-4.mr-4
        = f.label t('activerecord.attributes.user.last_name'), class: "form-label required"
        %div
          = f.label @client.last_name, class: "form-control"
      .form-group.ml-4.mr-4
        = f.label  t('activerecord.attributes.user.mail'), class: "form-label required"
        %div
          = f.label @client.email, class: "form-control"
      .form-group.ml-4.mr-4
        = f.label  t('activerecord.attributes.user.address'), class: "form-label required"
        %div
          = f.label @client.adress, class: "form-control"

      .form-group.ml-4.mr-4 
        = f.label t('activerecord.attributes.user.statu'), class: "form-label required"
        = f.select(:block, options_for_select(method_Block, @client.block),
                            {prompt: t('application.select')}, class: 'form-control')

        

      .row
        .offset-3.col-3
          = link_to t('application.back'), clients_path, class: "button_Back button_Back"
        .col-3
          = button_tag t('application.save'), class: "button_saving button_Back", 'data-disable-with': t('application.saving')

app/views/clients/edit.html.haml
.page_header
  %h1.mb-4
    = t('application.edit', model: t('activerecord.modules.client.one'))
= render "form"

app/views/clients/index.html.haml
.div.m-4
  .page.header
    %p{:style => "color: green"}= notice
    %h1.mb-4
      = t('application.list_of', model: t('activerecord.modules.client.other'))
  %div
    = search_form_for @q do |f|
    
      \#{f.search_field :name_cont, :type => "text2"}
      = button_tag( :class => "button button2") do
        Buscar
        %i.fa-solid.fa-magnifying-glass

      
  %div
    %table.table.table-striped
      %thread
        %tr
          %th= t('activerecord.attributes.user.name')
          %th= t('activerecord.attributes.user.last_name')
          %th= t('activerecord.attributes.user.mail')
          %th= t('activerecord.attributes.user.address')
          %th=  t('activerecord.attributes.user.statu')
          %th
          %th
          %th
      %tbody
        - @clients.each do |client|
          %tr
            %td= client.name
            %td= client.last_name
            %td= client.email
            %td= client.adress
            %td
              -if client.block == "enable"
                %i.fa_green.fa-solid.fa-lock-open.fa-1.5x
              -else 
                %i.fa_red.fa-solid.fa-lock.fa-1.5x
            %td
              = link_to  client_path(client) do
                %span{:title => t('application.show')}
                  %i.fa-black.fa-regular.fa-eye.fa-1.5x
                  
            %td
              = link_to edit_client_path(client) do
                %span{:title => t('application.edit')}
                  %i.fa-green.fa-regular.fa-pen-to-square  
            %td      

app/views/clients/show.html.haml
= render "layouts/flash"
.div.m-4
  .page.header_new
    %h2 
      =t('activerecord.modules.client.one')
    .card
      %img{:height => "250", :src => "https://img.icons8.com/windows/512/contacts.png", :width => "250"}/   
      .container
        %h5
          =t('activerecord.attributes.user.full_name')
          %p 
            = "#{@client.name}  #{@client.last_name}" 
        %h5 
          =t('activerecord.attributes.user.mail')
        %h5 
          %p 
            = @client.email
        %h5
          =t('activerecord.attributes.user.address')
        %h5 
          %p 
            =  @client.adress
        %h5
          =t('activerecord.attributes.user.statu')
        %h5 
          %p 
            = t("activerecord.attributes.dish.isEnable.#{@client.block}") 
    .row.mt-3
      .offset-3.col-3
        = link_to t('application.back'), clients_path, class: "button_Back button_Back"