config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :dishes
  resources :users
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  root  'sessions#new'

  scope module: :api, path: 'api' do
    resources :clients
    resources :dishes
    resources :order_details
    resources :users
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_one_attached :image
  enum isEnable: { disabled: 0, enable: 1 }
  validates :name, presence: true
  validates :cost, numericality: true, presence: true
  validates :description, presence: true
  validates :image, presence: true
  def image_url
    Rails.application.routes.url_helpers.url_for(image) if image.attached?
  end
end

app/controllers/api/dishes_controller.rb
module Api
  class DishesController < ApplicationController
    before_action :set_dish, only: %i[show edit update destroy]
    skip_before_action :verify_authenticity_token
    def index
      @q = Dish.ransack(params[:q])
      @dishes = @q.result
    end

    def show; end

    def new
      @dish = Dish.new
    end

    private

    def set_dish
      @dish = Dish.find(params[:id])
    end

    def dish_params
      params.require(:dish).permit(:name, :description, :cost, :isEnable, :image)
    end
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[show edit update destroy]

  def index
    @q = Dish.ransack(params[:q])
    @dishes = @q.result
  end

  def show; end

  def new
    @dish = Dish.new
  end

  def edit; end

  def create
    @dish = Dish.new(dish_params)

    if @dish.save
      flash[:success] = 'Dish was successfully created.'
      redirect_to dish_url(@dish)
    else
      flash[:danger] = 'Check the information'
      redirect_to new_dish_path
    end
  end

  def update
    if @dish.update(dish_params)
      flash[:success] = 'Dish was successfully edited.'
      redirect_to dish_url(@dish)
    else
      flash[:danger] = 'Check the information'
      redirect_to new_dish_path
    end
  end

  def destroy
    @dish.destroy

    flash[:success] = 'Dish was successfully destroyed.'
    redirect_to dishes_url
  end

  private

  def set_dish
    @dish = Dish.find(params[:id])
  end

  def dish_params
    params.require(:dish).permit(:name, :description, :cost, :isEnable, :image)
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
  def method_Enable
    Dish.isEnables.keys.map do |isEnable|
      [t("activerecord.attributes.dish.isEnable.#{isEnable}"), isEnable]
    end
  end
end

app/views/dishes/_form.html.haml
= render "layouts/flash"
.div.m-4
  .page.header_new
    = form_for @dish, validate: true do |f|
      .form-group.ml-4.mr-4
        = f.label t('activerecord.attributes.dish.name'), class: "form-label required"
        = f.text_field :name, autofocus: true, class: "form-control"
      .form-group.ml-4.mr-4
        = f.label t('activerecord.attributes.dish.description'), class: "form-label required"
        = f.text_field :description, autofocus: true, class: "form-control"
      .form-group.ml-4.mr-4
        = f.label  t('activerecord.attributes.dish.cost'), class: "form-label required"
        = f.text_field :cost, autofocus: true, class: "form-control"

      .form-group.ml-4.mr-4 
        = f.label t('activerecord.attributes.dish.condition'), class: "form-label required"
        = f.select(:isEnable, options_for_select(method_Enable, @dish.isEnable),
                            {prompt: t('application.select')}, class: 'form-control')
      %div>
        =f.file_field :image
        

      .row
        .offset-3.col-3
          = link_to t('application.back'), dishes_path, class: "button_Back button_Back"
        .col-3
          = button_tag t('application.save'), class: "button_saving button_Back", 'data-disable-with': t('application.saving')

app/views/dishes/index.html.haml
= render "layouts/flash"
.div.m-4
  .page.header
    %p{:style => "color: green"}= notice
    %h1.mb-4
      = t('application.list_of', model: t('activerecord.modules.dish.other'))
  %div
    = search_form_for @q do |f|
    
      \#{f.search_field :name_cont, :type => "text2"}
      = button_tag( :class => "button button2") do
        Buscar
        %i.fa-solid.fa-magnifying-glass

      .float-right
        = link_to t('application.new', model: t('activerecord.modules.dish.one')), new_dish_path, class: "button1 button2"
  %div
    %table.table.table-striped
      %thread
        %tr
          %th= t('activerecord.attributes.dish.name')
          %th= t('activerecord.attributes.dish.description')
          %th= t('activerecord.attributes.dish.cost')
          %th= t('activerecord.attributes.dish.condition')
          %th= t('activerecord.attributes.dish.image')
          %th
          %th
          %th
      %tbody
        - @dishes.each do |dish|
          %tr
            %td= dish.name
            %td= dish.description
            %td= dish.cost
            %td= t("activerecord.attributes.dish.isEnable.#{dish.isEnable}")
            %td= link_to image_tag(dish.image, size:'50'),image_tag(dish.image, size:'100')
            %td
              = link_to  dish_path(dish) do
                %span{:title => t('application.show')}
                  %i.fa-black.fa-regular.fa-eye.fa-1.5x
                  
            %td
              = link_to edit_dish_path(dish) do
                %span{:title => t('application.edit')}
                  %i.fa-green.fa-regular.fa-pen-to-square        

            %td 
              = link_to dish, method: :delete do
                %span{:title => t('application.delete')}
                  %i.fa-red.fa-solid.fa-trash

app/views/dishes/new.html.haml
.page_header
  %h1.mb-4
    = t('application.new', model: t('activerecord.modules.dish.one'))
= render "form"

app/views/dishes/show.html.haml
= render "layouts/flash"
.div.m-4
  .page.header
    %h2 Dish
    .card
      %img.img
        =image_tag(@dish.image, style: 'height:75%;width:100%;')
        .container
          %h3
            %b 
              = @dish.name
          %h4 
            =t('activerecord.attributes.dish.description')
          %h5 
            %p 
              = @dish.description
          %h6 
            =t('activerecord.attributes.dish.cost')
          %h7 
            %p 
              = @dish.cost
          %h6
            =t('activerecord.attributes.dish.condition')
          %h7 
            %p 
              =  t("activerecord.attributes.dish.isEnable.#{@dish.isEnable}")
    .row.mt-3
      .offset-3.col-3
        = link_to t('application.back'), dishes_path, class: "button_Back button_Back"